name: Tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install shards
        run: shards install
      - name: Build
        run: shards build
      - name: Check formatting
        run: crystal tool format --check
      - name: Run Ameba
        run: bin/ameba
      - name: Run tests
        run: crystal spec --define extended --order=random --error-on-warnings --verbose
